
spring.application.name=DailyDebugger



# Поврзување со PostgreSQL базата (промени го 'debuggle_db' со точниот назив на твојата база ако е поинаку)
spring.datasource.url=jdbc:postgresql://localhost:5432/daily_debugger_db
spring.datasource.username=postgres
spring.datasource.password=Enisa123!

# Твојот омилен Hibernate ddl-auto. За почеток 'update' е супер за само да си ги креира табелите
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ова овозможува автоматско читање на 'data.sql' при секое пуштање
spring.sql.init.mode=always
# Кажи му на Спринг прво да ги креира табелите од класите, па дури тогаш да ја пушти data.sql
spring.jpa.defer-datasource-initialization=true